### PR TITLE
Corrected name of email service from Mailgun to Mailjet

### PR DESCRIPTION
**Pull request by aleemaheer**

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by aleemaheer** [comment]
I was just following the tutorial and see the repository and notice this, so I decided to make a pull request 😍

**Comment by eddiejaoude** [comment]
Love it! Thank you! 🔥

**Comment by aleemaheer** [comment]
Can you tell me about the API_key that I have to put in the .env.local, where can I get that API key, from novu or mailjet?

**Comment by eddiejaoude** [comment]
In `.env.local` is your Novu key, Dima the co-founder explains and demos it here on a live stream
https://youtu.be/W2EybtWhZqo?t=3807

**Comment by aleemaheer** [comment]
Thank you 😊 I'll check it out

**Pull request merged**
